---
title: "Indi Joneson: Relictum"
company: Secret Escape Game
date: 22 Feb 2026 12:30
city: Frankfurt
country: Germany
long: 8.677559581792046
lat: 50.111860510923805
completion-time: 56 min
total-time: 60 min
rating: 3
clues: 4

about: 
  template: solana
  links: 
    - icon: globe2
      href: https://secretescapegame.com/en/relictum/


players:
  - Hanno
  - Fatima
  
cost: 100.98
currency: EUR
paid-by: Fatima

execute: 
  echo: false
  warning: false
  error: false
---

```{r}
#| label: map
#| out-width: 100%
#| fig-asp: 0.5

library(leaflet)

leaflet() %>% 
  addTiles() %>% 
  addProviderTiles('Esri.WorldGrayCanvas') %>% 
  addMarkers(lng = rmarkdown::metadata$long, 
             lat = rmarkdown::metadata$lat)
```

::::: columns
::: {.callout-important .column icon="false"}
## Fatima's impresssions

-   Puzzles were relatively nice

-   A few things around the room looked like potential puzzles, but were not. This created some confusion.

-   There was often a little lag between putting in right solution and seeing it's effect.

-   One of the doors were opened by one puzzle, but we didn't hear it open. Only after the game master told us that some door did open, did we start to look for it.

-   Few puzzles we could have gotten correct, if we were paying a bit more attention.

-   One of the items was used in three different puzzles.

Overall, I think the puzzles were interesting, but the hints to them a bit too confusing. Also, the puzzles weren't really that difficult; time was wasted on confusion.

The organization seemed a little lacking. Even though we arrived well on time, the game started later. The preparatory stage was a bit too messy, with not enough attention from the game masters and unclear procedure. I guess it is not really a place we'd gladly return to.
:::

::: {.callout-note .column icon="false"}
## Hanno's impressions

-   The escape room experience started with a rather long wait. Multiple groups were collected in the waiting area and given overview of basic rules and guided upstairs to tge escape rooms. This felt impersonal and disorganized.
-   The backstory for the room was very superficial. Same can be said about the overarching storyline.
-   Puzzles themselves were quite good and varied. However, there seemed to be quite some lag with dome of the elements, which caused dome confusion snd fustration.
:::
:::::
